version: '3'

services:
  postgres:
    container_name: gympoint-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gympoint
      - POSTGRES_PASSWORD=docker  

  redis:
    container_name: gympoint-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis: